name: Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  RUST_BACKTRACE: 1
  PRUSTI_ASSERT_TIMEOUT: 60000

jobs:

# quick-test:
#   runs-on: ubuntu-latest
#   steps:
#   - name: Check out the repo
#     uses: actions/checkout@v2
#   - name: Prepare environment
#     run: .github/workflows/prepare-environment.sh
#   - name: Build with cargo
#     run: cargo build --all --verbose
#   - name: Run cargo tests
#     run: cargo test -p prusti --verbose
#     env:
#       TESTNAME: quick/

# full-test:
#   runs-on: ubuntu-latest
#   steps:
#   - name: Check out the repo
#     uses: actions/checkout@v2
#   - name: Prepare environment
#     run: .github/workflows/prepare-environment.sh
#   - name: Run cargo tests
#     run: cargo test --all --verbose
#   - name: Run tests with prusti-rustc
#     run: |
#       ./target/debug/prusti-rustc prusti/tests/verify/pass/no-annotations/assert-true.rs
#       ! ./target/debug/prusti-rustc prusti/tests/verify/fail/no-annotations/assert-false.rs

  rustc-update-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up the environment
      run: ./x.py setup
    - name: Build with cargo
      run: ./x.py build --all --verbose
    - name: Run cargo tests
      run: ./x.py test --all --verbose
    - name: Check formatting
      run: echo "temporarily skipped" # ./x.py fmt -- --check
    - name: Check prusti-contracts
      run: |
        cd prusti-contracts-test/
        cargo build

  rustc-update-mac:
    runs-on: macos-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up the environment
      run: ./x.py setup
    - name: Build with cargo
      run: ./x.py build --all --verbose
    - name: Run cargo tests
      run: ./x.py test --all --verbose
    - name: Check formatting
      run: echo "temporarily skipped" # ./x.py fmt -- --check
    - name: Check prusti-contracts
      run: |
        cd prusti-contracts-test/
        cargo build
